[package]
name = "lure"
version = "0.1.0"
edition = "2024"

[lib]
name = "lure"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
regex.workspace = true

lure-macros = { path = "../lure-macros" }
